### ISSUE TITLE
Is Release 1.0.9 compatible with CANedge2 1.7.1?

### ISSUE THREAD

**Issue by swaaws** [CSS-Electronics/api-examples#17]
1.7.1 recorded mdf:
```console
(env) user@vm$ python process_tp_data.py 
Traceback (most recent call last):
  File "/home/user/Downloads/api-examples-1.0.9/examples/data-processing/process_tp_data.py", line 38, in <module>
    process_tp_example(devices, dbc_paths, "uds")
  File "/home/user/Downloads/api-examples-1.0.9/examples/data-processing/process_tp_data.py", line 17, in process_tp_example
    df_raw, device_id = proc.get_raw_data(log_file)
  File "/home/user/Downloads/api-examples-1.0.9/examples/data-processing/utils.py", line 230, in get_raw_data
    df_raw = mdf_file.get_data_frame()
RuntimeError: An unexpected error occurred while obtaining a CAN iterator: Not finalized?

```
1.6.1  recorded mdf:
```console
(env) user@vm$ python process_tp_data.py 
Finished saving CSV output for devices: ['//LOG/2F6913DB']
(env) user@vm$ 
```

**Comment by MatinF** [comment]
Hi, the release 01.07.01 for the CANedge requires an update to the Python API modules. This update has not yet been released, but is targeted for release in January 2023. We will add an updated api-examples release once the update is out.

**Comment by MatinF** [comment]
Closing this as it has been resolved by more recent releases
